# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    config.vm.box = "impel1o/centos-7-8"
  
  #  config.vm.provision "ansible" do |ansible|
  #    ansible.verbose = "vvv"
  #    ansible.playbook = "playbook.yml"
  #    ansible.become = "true"
  #  end
  
    config.vm.provider "virtualbox" do |v|
      v.memory = 40248
      v.cpus = 4
    end
  
    config.vm.define "boot" do |nfss|
      nfss.vm.network "private_network", ip: "192.168.50.10", virtualbox__intnet: "net1"
      nfss.vm.hostname = "boot"
    end
  
  end
  